language: node_js
services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
script:
  - npm install
  - npm run coveralls
env:
  global:
    - DATABASE_TEST=test_db
notifications:
  slack: synaxisworkspace:Xw0MSErrrNIbV0CauFzaPHho
